# Change these first
owner: paulluxford # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: WPGeni
    url: https://wpgeni.com
  - name: GCBW
    url: https://goldcoastbusinesswebsites.com.au
  - name: Redefining Health
    url: https://redefininghealth.com.au
  - name: Professional Pest Manager
    url: https://professionalpestmanager.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /uptime
  theme: ocean
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "**Uptime** is the uptime monitor for WPGeni website care clients."
  introMessage: This is a very cool tool.
  navbar:
    - title: Status
      href: https://paulluxford.github.io/uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Website
      href: https://wpgeni.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
