# Change these first
owner: paulluxford # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: WPGeni
    url: https://wpgeni.com
  - name: GCBW
    url: https://goldcoastbusinesswebsites.com.au
  - name: Redefining Health
    url: https://redefininghealth.com.au
  - name: Professional Pest Manager
    url: https://professionalpestmanager.com
  - name: Blinds 2 Go
    url: https://www.blinds2go.com.au/
  - name: Creative Dance Academy
    url: https://creativedance.com.au/
  - name: HHH
    url: https://hhh.com.au/
  - name: Integrated Health Specialists
    url: https://integratedhealthspecialists.com.au/
  - name: Manns Pest Control
    url: https://www.mannspestcontrol.com.au/
  - name: Nautilus Law
    url: https://nautiluslaw.com.au/
  - name: Resolve Pest Control
    url: https://www.resolvepestcontrol.com.au/
  - name: Richards Pest Control
    url: https://richardspestcontrol.com.au/
  - name: Rose Petals
    url: http://rosepetals.com.au/
  - name: The Flower Factory
    url: http://theflowerfactory.com.au/
  # - name: 
  #  url:

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /uptime
  theme: light
  logoUrl: https://wpgeni.com/wp-content/uploads/2022/03/wpgeni-large-logo-orange.svg
  favicon: https://wpgeni.com/wp-content/uploads/2017/11/favicon.png
  name: Uptime
  introTitle: "This is the uptime monitor for **WPGeni** website care clients."
  introMessage: This is a very cool tool.
  navbar:
    - title: Status
      href: https://paulluxford.github.io/uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Website
      href: https://wpgeni.com
      
workflowSchedule:
  uptime: "*/15 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
